name: FarmProtect
version: 1.9.0
description: Stops farmland, plots , soil turning back to dirt
author: jacklin213

main: me.jacklin213.farmprotect.FarmProtect

commands:
  farmprotect:
    description: Used for reload command
    aliases: fp
 
permissions:
  farmprotect.reload:
    description: Allows the usage of the reload command
    default: op
  farmprotect.addworld:
    default: op
  farmprotect.removeworld:
    default: op
  farmprotect.toggle.*:
    default: op
    children:
        farmprotect.multiworld.toggle: true
        farmprotect.explosionprotect.toggle: true
  farmprotect.multiworld.toggle:
    default: op
  farmprotect.explosionprotect.toggle:
    default: op