name: FarmProtect
version: 1.7.9
description: Stops farmland, plots , soil turning back to dirt
author: jacklin213

main: me.jacklin213.farmprotect.FarmProtect

commands:
  farmprotect:
    description: Used for reload command
 
permissions:
  farmprotect.reload:
    description: Allows the usage of the reload command
    default: op